server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
datasource:
  url: jdbc:mysql://localhost:3306/boot
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: root
  initial-size: 10
  max-active: 20
  max-idle: 8
  min-idle: 8
spring:
  security:
    user:
      password: admin
      name: admin